use_frameworks!

platform :ios, '9.0'

target 'AMLoadingAnimation_Example' do
  pod 'AMLoadingAnimation', :path => '../'

  target 'AMLoadingAnimation_Tests' do
    inherit! :search_paths

    
  end
end
